server:
  port: 4000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/warzenhof
    username: sa
    password: 1
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  liquibase:
    changeLog: classpath:db/db.changelog-master.xml
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug
