POST http://localhost:4000/create
Content-Type: application/json

{
  "name": "Mobrid Egnel!"
}


POST http://localhost:4000/create
Content-Type: application/json

{
  "name": "Knibel Knorz"
}


POST http://localhost:4000/create
Content-Type: application/json

{
  "text": "Maybaum"
}


GET http://localhost:4000/