CREATE TABLE if not exists BLOGENTRY (
    ID LONG NOT NULL AUTO_INCREMENT,
    CONTENT VARCHAR(100) NOT NULL,
    CREATED DATE NOT NULL,
    UPDATED DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE if not exists DISH (
     ID LONG NOT NULL AUTO_INCREMENT,
     NAME VARCHAR(100) NOT NULL,
     PRIMARY KEY (ID)
);